### ISSUE TITLE
Question about possible performance improvement

### ISSUE THREAD

**Issue by srutzky** [nthdeveloper/RichTextStripper#3]
Hi there. In updating the code for issue #1 / #2 I noticed something that might could be improved, but I'm not sure and didn't want to make any changes without fully understanding how the code should work in all cases (not just the cases that I am aware of).

On line **119** the `_outputTextList` variable is created as `List<string>()`:

https://github.com/nthdeveloper/RichTextStripper/blob/d8a4508570f23ea6456b89075aa75c35a7e38424/RichTextStripper.cs#L119

Items are added to this collection as each piece is parsed, and finally all of those items are combined into a single string on line **250**:

https://github.com/nthdeveloper/RichTextStripper/blob/d8a4508570f23ea6456b89075aa75c35a7e38424/RichTextStripper.cs#L250

My question is: why is this not a `StringBuilder`? A `StringBuilder` would be more efficient, and can handle appending `char`, `string`, etc.

Is there a technical reason that this is a `List<string>()`? If not, I (or someone else) can change it to be a `StringBuilder`.

**Comment by srutzky** [comment]
@thamathar Just FYI...

**Comment by nthdeveloper** [comment]
@srutzky there is no special reason for using List<string>. Probably it was a list of strings in the original code and I did not change it. It seems, it can be safely replaced with StringBuilder.

**Comment by nthdeveloper** [comment]
Now uses StringBuilder.
