### ISSUE TITLE
Exception trying to pop from empty stack ( '}' without a corresponding '{' )

### ISSUE THREAD

**Issue by lwestfall** [nthdeveloper/RichTextStripper#5]
Been using this in production for a couple of years now, it's been run on tens of thousands of strings. Thanks for translating and refining this. It's been doing it's job quietly and effectively the whole time. Until today.

A string was passed in that has an closing curly brace without an opening brace beforehand. This caused the below to throw an InvalidOperationException as it tries to pop from an empty stack.

Want me to do PR? I'd basically just wrap everything in this `else if` in a try catch (that does nothing with the exception). Of course this would ignore the other edge case where there is an opening curly brace without a corresponding closing brace, which shouldn't throw an exception but still might have ungraceful results. So in that case maybe a little more thought is needed.

Anyway, here's the culprit:

https://github.com/nthdeveloper/RichTextStripper/blob/1f7c38018bb563339855886605d0e67d0eafca5c/RichTextStripper.cs#L150

**Comment by nthdeveloper** [comment]
Added a quick fix by checking if there is something in the stack. Feel free to create a pull request with your solution if this doesn't help or you find better solution.

**Comment by lwestfall** [comment]
This works! Thanks
